// P3 "honest uninstall" completeness tests.
//
// Verifies that cleanPlatforms() removes the IJFW MCP entry from ALL 15
// platforms (with focus on the 8 previously-missing ones) and that
// stripRegisteredProjectBlocks() strips IJFW marker regions from registered
// project CLAUDE.md / AGENTS.md + cwd rules files while preserving every
// user-authored line and creating backups.
//
// Style (a): import the exported functions and drive them against a scratch
// sandbox (injected home/cwd/registryPath). No subprocess -> deterministic, no
// spawn flake, and the real $HOME is never touched.
//
// Run: node --test test/uninstall-completeness.test.mjs

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync, existsSync,
  readdirSync, copyFileSync,
} from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

import {
  stripIjfwRegions,
  cleanPlatforms,
  stripRegisteredProjectBlocks,
  parseRegistryPaths,
  resolveAiderTemplate,
  removeAiderFileIfPristine,
} from '../src/uninstall.js';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), '..', '..');

function write(p, content) {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

function hasBackup(p) {
  // A `<file>.bak.<TS>` sibling exists.
  const dir = dirname(p);
  const base = p.split('/').pop();
  if (!existsSync(dir)) return false;
  return readdirSync(dir).some((n) => n.startsWith(base + '.bak.'));
}

// ---------------------------------------------------------------------------
// stripIjfwRegions: pure region surgery
// ---------------------------------------------------------------------------

describe('stripIjfwRegions (pure)', () => {
  it('strips CLAUDE.md MEMORY region (parenthetical start tag) and keeps user content', () => {
    const src = [
      '# My Project',
      '',
      'My own notes here.',
      '',
      '<!-- IJFW-MEMORY-START (managed -- do not edit manually) -->',
      '<ijfw-memory>',
      'project memory blah',
      '</ijfw-memory>',
      '<!-- IJFW-MEMORY-END -->',
      '',
      'More of my notes.',
      '',
    ].join('\n');
    const { text, changed } = stripIjfwRegions(src);
    assert.equal(changed, true);
    assert.ok(text.includes('# My Project'));
    assert.ok(text.includes('My own notes here.'));
    assert.ok(text.includes('More of my notes.'));
    assert.ok(!text.includes('IJFW-MEMORY-START'));
    assert.ok(!text.includes('IJFW-MEMORY-END'));
    assert.ok(!text.includes('ijfw-memory'));
  });

  it('strips bare AGENTS.md regions + explainer (Four/Five count word) + autogen comment', () => {
    const src = [
      '# AGENTS',
      'Five IJFW-managed regions live in this file. Content outside the markers is',
      'yours -- IJFW will never touch it.',
      '',
      '<!-- IJFW-MEMORY-START -->',
      'x',
      '<!-- IJFW-MEMORY-END -->',
      '',
      '<!-- IJFW-ROUTING-START -->',
      'y',
      '<!-- IJFW-ROUTING-END -->',
      '<!-- Auto-generated by IJFW from repo scan. Edit freely. -->',
      'user tail',
      '',
    ].join('\n');
    const { text, changed } = stripIjfwRegions(src);
    assert.equal(changed, true);
    assert.ok(text.includes('# AGENTS'));
    assert.ok(text.includes('user tail'));
    assert.ok(!text.includes('IJFW-managed regions'));
    assert.ok(!text.includes('Auto-generated by IJFW'));
    assert.ok(!text.includes('IJFW-ROUTING'));
  });

  it('is a no-op (changed=false) on text with no IJFW markers', () => {
    const src = '# Plain\n\nNothing to see.\n';
    const { text, changed } = stripIjfwRegions(src);
    assert.equal(changed, false);
    assert.equal(text, src);
  });
});

// ---------------------------------------------------------------------------
// parseRegistryPaths
// ---------------------------------------------------------------------------

describe('parseRegistryPaths', () => {
  let dir;
  before(() => { dir = mkdtempSync(join(tmpdir(), 'ijfw-reg-')); });
  after(() => { rmSync(dir, { recursive: true, force: true }); });

  it('returns [] when the registry is absent', () => {
    assert.deepEqual(parseRegistryPaths(join(dir, 'nope.md')), []);
  });

  it('parses path field, skips blank/malformed lines', () => {
    const reg = join(dir, 'registry.md');
    write(reg, [
      '/abs/project-a | hash1 | 2026-06-08T00:00:00Z',
      '',
      '   ',
      'not-an-abs-path | hash | iso',
      '/abs/project-b | hash2 | 2026-06-08T00:00:01Z',
    ].join('\n'));
    assert.deepEqual(parseRegistryPaths(reg), ['/abs/project-a', '/abs/project-b']);
  });
});

// ---------------------------------------------------------------------------
// cleanPlatforms: 8 newly-covered platforms
// ---------------------------------------------------------------------------

describe('cleanPlatforms — 8 newly-covered platforms', () => {
  let home;
  let cwd;
  const ijfwEntry = { command: 'node', args: ['/x/server.js'] };

  before(() => {
    home = mkdtempSync(join(tmpdir(), 'ijfw-home-'));
    cwd = mkdtempSync(join(tmpdir(), 'ijfw-cwd-'));

    // Qwen (flat mcpServers) — plus a user MCP that must survive.
    write(join(home, '.qwen', 'settings.json'), JSON.stringify({
      mcpServers: { 'ijfw-memory': ijfwEntry, 'user-tool': { command: 'x' } },
    }));
    // Kimi (flat mcpServers).
    write(join(home, '.kimi', 'mcp.json'), JSON.stringify({
      mcpServers: { 'ijfw-memory': ijfwEntry },
    }));
    // Antigravity IDE + CLI (flat mcpServers).
    write(join(home, '.gemini', 'antigravity', 'mcp_config.json'), JSON.stringify({
      mcpServers: { 'ijfw-memory': ijfwEntry },
    }));
    write(join(home, '.gemini', 'config', 'mcp_config.json'), JSON.stringify({
      mcpServers: { 'ijfw-memory': ijfwEntry },
    }));
    // OpenCode (nested mcp.ijfw-memory) + user entry.
    write(join(home, '.config', 'opencode', 'opencode.json'), JSON.stringify({
      mcp: { 'ijfw-memory': { type: 'local', command: ['node', '/x'] }, 'user-mcp': {} },
    }));
    // OpenClaw (nested mcp.servers.ijfw-memory).
    write(join(home, '.openclaw', 'openclaw.json'), JSON.stringify({
      mcp: { servers: { 'ijfw-memory': ijfwEntry } },
    }));
    // Pi (AGENTS.md with marker region + user content).
    write(join(home, '.pi', 'agent', 'AGENTS.md'), [
      '# Pi rules',
      'User keeps this.',
      '<!-- IJFW-ROUTING-START -->',
      'routing',
      '<!-- IJFW-ROUTING-END -->',
      '',
    ].join('\n'));

    // Aider PRISTINE conf (byte-match the shipped template) -> should be removed.
    copyFileSync(join(REPO_ROOT, 'aider', 'aider.conf.yml'), join(home, '.aider.conf.yml'));
    // Aider MODIFIED CONVENTIONS (differs) -> must be KEPT.
    write(join(home, 'CONVENTIONS.md'), 'I edited this myself.\n');
  });

  after(() => {
    rmSync(home, { recursive: true, force: true });
    rmSync(cwd, { recursive: true, force: true });
  });

  it('removes ijfw-memory from all 8 and preserves user entries + Aider safety', () => {
    const removed = cleanPlatforms({ home, cwd, repoRoot: REPO_ROOT });

    // Qwen — ijfw gone, user-tool survives.
    const qwen = JSON.parse(readFileSync(join(home, '.qwen', 'settings.json'), 'utf8'));
    assert.ok(!qwen.mcpServers['ijfw-memory']);
    assert.ok(qwen.mcpServers['user-tool']);

    // Kimi.
    const kimi = JSON.parse(readFileSync(join(home, '.kimi', 'mcp.json'), 'utf8'));
    assert.ok(!kimi.mcpServers['ijfw-memory']);

    // Antigravity IDE + CLI.
    const agIde = JSON.parse(readFileSync(join(home, '.gemini', 'antigravity', 'mcp_config.json'), 'utf8'));
    const agCli = JSON.parse(readFileSync(join(home, '.gemini', 'config', 'mcp_config.json'), 'utf8'));
    assert.ok(!agIde.mcpServers['ijfw-memory']);
    assert.ok(!agCli.mcpServers['ijfw-memory']);

    // OpenCode — nested ijfw gone, user-mcp survives.
    const oc = JSON.parse(readFileSync(join(home, '.config', 'opencode', 'opencode.json'), 'utf8'));
    assert.ok(!oc.mcp['ijfw-memory']);
    assert.ok(oc.mcp['user-mcp']);

    // OpenClaw — nested ijfw gone.
    const ocw = JSON.parse(readFileSync(join(home, '.openclaw', 'openclaw.json'), 'utf8'));
    assert.ok(!ocw.mcp.servers['ijfw-memory']);

    // Pi — region stripped, user content preserved.
    const pi = readFileSync(join(home, '.pi', 'agent', 'AGENTS.md'), 'utf8');
    assert.ok(pi.includes('# Pi rules'));
    assert.ok(pi.includes('User keeps this.'));
    assert.ok(!pi.includes('IJFW-ROUTING'));

    // Aider: pristine conf removed, modified CONVENTIONS kept.
    assert.ok(!existsSync(join(home, '.aider.conf.yml')), 'pristine aider conf should be removed');
    assert.ok(existsSync(join(home, 'CONVENTIONS.md')), 'modified CONVENTIONS must be kept');
    assert.equal(readFileSync(join(home, 'CONVENTIONS.md'), 'utf8'), 'I edited this myself.\n');

    // Backups created for files we edited.
    assert.ok(hasBackup(join(home, '.qwen', 'settings.json')), 'qwen backup');
    assert.ok(hasBackup(join(home, '.pi', 'agent', 'AGENTS.md')), 'pi backup');

    // Honest summary mentions the kept Aider file.
    assert.ok(removed.some((l) => l.includes('CONVENTIONS.md') && l.includes('KEPT')));
  });

  it('is a no-op on an absent home (never throws, returns [] or harmless lines)', () => {
    const emptyHome = mkdtempSync(join(tmpdir(), 'ijfw-empty-'));
    const emptyCwd = mkdtempSync(join(tmpdir(), 'ijfw-emptycwd-'));
    try {
      // Should not throw on entirely missing config tree.
      const removed = cleanPlatforms({ home: emptyHome, cwd: emptyCwd, repoRoot: REPO_ROOT });
      assert.ok(Array.isArray(removed));
    } finally {
      rmSync(emptyHome, { recursive: true, force: true });
      rmSync(emptyCwd, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Aider template resolution across repo + tarball/dist layouts.
//
// The published @ijfw/install package does NOT ship the repo's top-level
// `aider/` dir. build.js stages the two convention templates into
// installer/templates/aider/ (declared in package.json "files") and
// resolveAiderTemplate() finds them in BOTH layouts so the pristine-byte
// compare actually runs in a pure-tarball install.
// ---------------------------------------------------------------------------

describe('Aider template resolution (repo + dist layouts)', () => {
  it('resolves the shipped template from the git-repo layout (<repoRoot>/aider/)', () => {
    const conf = resolveAiderTemplate('aider.conf.yml', REPO_ROOT);
    const conv = resolveAiderTemplate('CONVENTIONS.md', REPO_ROOT);
    assert.ok(conf && existsSync(conf), 'aider.conf.yml resolves under repo layout');
    assert.ok(conv && existsSync(conv), 'CONVENTIONS.md resolves under repo layout');
  });

  it('resolves the shipped template from a simulated dist/tarball layout', () => {
    // Simulate a pure tarball: a package root with NO top-level aider/ dir but
    // WITH templates staged under installer/templates/aider/ (what build.js does
    // and what package.json "files" ships). Point repoRoot at this scratch root.
    const pkg = mkdtempSync(join(tmpdir(), 'ijfw-distpkg-'));
    try {
      const tplDir = join(pkg, 'installer', 'templates', 'aider');
      mkdirSync(tplDir, { recursive: true });
      writeFileSync(join(tplDir, 'aider.conf.yml'), 'shipped-conf\n');
      writeFileSync(join(tplDir, 'CONVENTIONS.md'), 'shipped-conv\n');
      // NB: pkg/aider/ deliberately does NOT exist (mirrors the tarball gap).
      assert.ok(!existsSync(join(pkg, 'aider')), 'guard: no top-level aider/ in sim tarball');

      const conf = resolveAiderTemplate('aider.conf.yml', pkg);
      const conv = resolveAiderTemplate('CONVENTIONS.md', pkg);
      assert.ok(conf && existsSync(conf), 'conf resolves from staged templates/aider/');
      assert.ok(conv && existsSync(conv), 'conv resolves from staged templates/aider/');
      assert.equal(readFileSync(conf, 'utf8'), 'shipped-conf\n');
    } finally {
      rmSync(pkg, { recursive: true, force: true });
    }
  });

  it('built dist/uninstall.js resolves the staged template (production tarball path)', async () => {
    // The real fix: in a pure tarball, REPO_ROOT points OUTSIDE the package and
    // no top-level aider/ exists -- resolution must fall through to the
    // __dirname-relative templates/aider/ that build.js stages. Import the BUILT
    // dist module and pass a bogus repoRoot so ONLY the dist fallback can match.
    const distPath = join(REPO_ROOT, 'installer', 'dist', 'uninstall.js');
    if (!existsSync(distPath)) {
      // dist not built in this checkout -- the src-layout coverage above plus
      // the build step (npm run build) exercise the same code path. Skip rather
      // than fail a non-built tree.
      return;
    }
    const distUrl = pathToFileURL(distPath).href;
    const mod = await import(distUrl);
    const p = mod.resolveAiderTemplate('aider.conf.yml', '/nonexistent-repo-root-xyz');
    assert.ok(p && existsSync(p), 'dist fallback resolves staged templates/aider/');
    assert.ok(
      p.includes(join('templates', 'aider')),
      'resolved via the staged templates/aider/ location',
    );
  });

  it('KEEPS the user file when no template is located (safety contract)', () => {
    // When resolveAiderTemplate finds nothing it returns '' and the byte-compare
    // can no longer prove IJFW-authorship -> the file MUST be kept, never
    // deleted. Drive the contract directly with an empty template path.
    const home = mkdtempSync(join(tmpdir(), 'ijfw-keepsafe-'));
    try {
      writeFileSync(join(home, '.aider.conf.yml'), 'anything\n');
      const result = removeAiderFileIfPristine(join(home, '.aider.conf.yml'), '');
      assert.equal(result, 'kept-modified', 'no template -> cannot prove -> keep');
      assert.ok(existsSync(join(home, '.aider.conf.yml')), 'user file must survive');
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  it('byte-compare removes a pristine file and KEEPS a modified one (dist-located template)', () => {
    // End-to-end of the actual gap: pristine ~/.aider.conf.yml byte-matching a
    // template found only in the staged (dist) location is removed; a modified
    // CONVENTIONS.md is kept.
    const home = mkdtempSync(join(tmpdir(), 'ijfw-aiderhome-'));
    const pkg = mkdtempSync(join(tmpdir(), 'ijfw-aiderpkg-'));
    try {
      const tplDir = join(pkg, 'installer', 'templates', 'aider');
      mkdirSync(tplDir, { recursive: true });
      const PRISTINE = 'model: gpt-4\nread: CONVENTIONS.md\n';
      writeFileSync(join(tplDir, 'aider.conf.yml'), PRISTINE);
      writeFileSync(join(tplDir, 'CONVENTIONS.md'), 'canonical conventions\n');

      // User home: a pristine conf (byte-identical) + a modified conventions.
      writeFileSync(join(home, '.aider.conf.yml'), PRISTINE);
      writeFileSync(join(home, 'CONVENTIONS.md'), 'I changed this.\n');

      const confTpl = resolveAiderTemplate('aider.conf.yml', pkg);
      const convTpl = resolveAiderTemplate('CONVENTIONS.md', pkg);

      const confResult = removeAiderFileIfPristine(join(home, '.aider.conf.yml'), confTpl);
      const convResult = removeAiderFileIfPristine(join(home, 'CONVENTIONS.md'), convTpl);

      assert.equal(confResult, 'removed', 'pristine conf removed');
      assert.ok(!existsSync(join(home, '.aider.conf.yml')), 'pristine conf gone from disk');
      assert.equal(convResult, 'kept-modified', 'modified conventions kept');
      assert.ok(existsSync(join(home, 'CONVENTIONS.md')), 'modified conventions still on disk');
      assert.equal(readFileSync(join(home, 'CONVENTIONS.md'), 'utf8'), 'I changed this.\n');
    } finally {
      rmSync(home, { recursive: true, force: true });
      rmSync(pkg, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// stripRegisteredProjectBlocks: project CLAUDE.md / AGENTS.md + rules
// ---------------------------------------------------------------------------

describe('stripRegisteredProjectBlocks', () => {
  let home;
  let cwd;
  let proj;

  before(() => {
    home = mkdtempSync(join(tmpdir(), 'ijfw-rhome-'));
    cwd = mkdtempSync(join(tmpdir(), 'ijfw-rcwd-'));
    proj = mkdtempSync(join(tmpdir(), 'ijfw-proj-'));

    // Registry points at the fake project.
    write(join(home, '.ijfw', 'registry.md'), [
      `${proj} | abc123 | 2026-06-08T00:00:00Z`,
      '/does/not/exist | dead | 2026-06-08T00:00:01Z',
      '',
    ].join('\n'));

    // Polluted project CLAUDE.md (user content + IJFW region).
    write(join(proj, 'CLAUDE.md'), [
      '# Project Context',
      'Stack: my own stack',
      '',
      '<!-- IJFW-MEMORY-START (managed -- do not edit manually) -->',
      '<ijfw-memory>',
      'injected',
      '</ijfw-memory>',
      '<ijfw-routing>',
      'route',
      '</ijfw-routing>',
      '<!-- IJFW-MEMORY-END -->',
      '',
      'My tail content.',
      '',
    ].join('\n'));

    // Polluted project AGENTS.md.
    write(join(proj, 'AGENTS.md'), [
      '# Agents',
      'user line',
      '<!-- IJFW-AGENTS-START -->',
      'agents block',
      '<!-- IJFW-AGENTS-END -->',
      '',
    ].join('\n'));

    // cwd rules files.
    write(join(cwd, '.cursor', 'rules', 'ijfw.mdc'), 'wholly ijfw\n');
    write(join(cwd, '.windsurfrules'), [
      'user windsurf prefs',
      '<!-- IJFW-ROUTING-START -->',
      'r',
      '<!-- IJFW-ROUTING-END -->',
      '',
    ].join('\n'));
    // Copilot file that is WHOLLY an IJFW region -> becomes empty -> deleted.
    write(join(cwd, '.github', 'copilot-instructions.md'), [
      '<!-- IJFW-MEMORY-START -->',
      'only ijfw',
      '<!-- IJFW-MEMORY-END -->',
      '',
    ].join('\n'));
  });

  after(() => {
    rmSync(home, { recursive: true, force: true });
    rmSync(cwd, { recursive: true, force: true });
    rmSync(proj, { recursive: true, force: true });
  });

  it('strips project blocks, preserves user content, handles rules files, backs up', () => {
    const results = stripRegisteredProjectBlocks({
      home, cwd, registryPath: join(home, '.ijfw', 'registry.md'),
    });

    // Project CLAUDE.md — region gone, user content intact.
    const claude = readFileSync(join(proj, 'CLAUDE.md'), 'utf8');
    assert.ok(claude.includes('# Project Context'));
    assert.ok(claude.includes('Stack: my own stack'));
    assert.ok(claude.includes('My tail content.'));
    assert.ok(!claude.includes('IJFW-MEMORY'));
    assert.ok(!claude.includes('ijfw-memory'));
    assert.ok(!claude.includes('ijfw-routing'));

    // Project AGENTS.md.
    const agents = readFileSync(join(proj, 'AGENTS.md'), 'utf8');
    assert.ok(agents.includes('# Agents'));
    assert.ok(agents.includes('user line'));
    assert.ok(!agents.includes('IJFW-AGENTS'));

    // cwd: cursor rule deleted wholesale.
    assert.ok(!existsSync(join(cwd, '.cursor', 'rules', 'ijfw.mdc')), 'cursor rule deleted');

    // cwd: windsurf rules region stripped, user prefs kept (file survives).
    const ws = readFileSync(join(cwd, '.windsurfrules'), 'utf8');
    assert.ok(ws.includes('user windsurf prefs'));
    assert.ok(!ws.includes('IJFW-ROUTING'));

    // cwd: copilot file was wholly IJFW -> deleted (became empty).
    assert.ok(!existsSync(join(cwd, '.github', 'copilot-instructions.md')), 'empty copilot file deleted');

    // Backups created for files we rewrote.
    assert.ok(hasBackup(join(proj, 'CLAUDE.md')), 'CLAUDE.md backup');
    assert.ok(hasBackup(join(proj, 'AGENTS.md')), 'AGENTS.md backup');

    // Summary is non-empty and human-readable.
    assert.ok(results.length >= 5);
  });

  it('returns [] when registry is missing (no-op)', () => {
    const h2 = mkdtempSync(join(tmpdir(), 'ijfw-noreg-'));
    const c2 = mkdtempSync(join(tmpdir(), 'ijfw-noregcwd-'));
    try {
      const results = stripRegisteredProjectBlocks({
        home: h2, cwd: c2, registryPath: join(h2, '.ijfw', 'registry.md'),
      });
      assert.deepEqual(results, []);
    } finally {
      rmSync(h2, { recursive: true, force: true });
      rmSync(c2, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Memory preservation is owned by main()'s purge/stash logic, but assert the
// strip paths never touch a memory/ dir under home.
// ---------------------------------------------------------------------------

describe('memory/ preservation', () => {
  it('cleanPlatforms + strip never touch ~/.ijfw/memory/', () => {
    const home = mkdtempSync(join(tmpdir(), 'ijfw-memhome-'));
    const cwd = mkdtempSync(join(tmpdir(), 'ijfw-memcwd-'));
    try {
      write(join(home, '.ijfw', 'memory', 'MEMORY.md'), '# my memory\nkeep me\n');
      write(join(home, '.qwen', 'settings.json'), JSON.stringify({
        mcpServers: { 'ijfw-memory': { command: 'node', args: ['/x'] } },
      }));
      cleanPlatforms({ home, cwd, repoRoot: REPO_ROOT });
      stripRegisteredProjectBlocks({ home, cwd, registryPath: join(home, '.ijfw', 'registry.md') });
      assert.ok(existsSync(join(home, '.ijfw', 'memory', 'MEMORY.md')));
      assert.equal(readFileSync(join(home, '.ijfw', 'memory', 'MEMORY.md'), 'utf8'), '# my memory\nkeep me\n');
    } finally {
      rmSync(home, { recursive: true, force: true });
      rmSync(cwd, { recursive: true, force: true });
    }
  });
});
