#!/usr/bin/env bash
# generate-manifest.sh -- emit SHA-256 manifest for the Hermes IJFW plugin.
#
# Mirror of wayland/plugins/ijfw/scripts/generate-manifest.sh. Identical
# format and contract -- byte-stable LC_ALL=C output, atomic rename.
#
#     cd hermes/plugins/ijfw && LC_ALL=C sha256sum -c manifest.sha256
#
# The manifest is the deterministic baseline of the V3-F7 signing chain.
# The ed25519 signature + GitHub OIDC attestation layer rides on top of
# this manifest at install time.
#
# Files included MUST match _manifest.MANIFESTED_FILES exactly:
#   __init__.py, _handlers.py, _strings.py, _mcp.py,
#   _context_engine.py, _manifest.py
#
# Files excluded:
#   - tests/ (not loaded by the live agent)
#   - __pycache__/ (regenerated per-Python-version)
#   - manifest.sha256 itself (cannot sign itself)
#   - scripts/ (build-time, not load-time)

set -euo pipefail

# Force C locale for byte-stable ordering and digest output across hosts.
export LC_ALL=C
export LANG=C

# Resolve plugin directory: parent of this script's parent.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PLUGIN_DIR}"

MANIFESTED_FILES=(
  "__init__.py"
  "_handlers.py"
  "_strings.py"
  "_mcp.py"
  "_context_engine.py"
  "_manifest.py"
)

# Pick a digest tool. macOS ships shasum; Linux ships sha256sum. Both emit
# the same `<hex>  <path>` two-space format we parse in _manifest.py.
if command -v sha256sum >/dev/null 2>&1; then
  HASHER="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  HASHER="shasum -a 256"
else
  echo "generate-manifest.sh: neither sha256sum nor shasum found in PATH" >&2
  exit 1
fi

TMP="${PLUGIN_DIR}/manifest.sha256.tmp"
DEST="${PLUGIN_DIR}/manifest.sha256"

{
  printf '# IJFW Hermes plugin manifest -- generated by scripts/generate-manifest.sh\n'
  printf '# Verify: cd hermes/plugins/ijfw && LC_ALL=C sha256sum -c manifest.sha256\n'
  for f in "${MANIFESTED_FILES[@]}"; do
    if [ ! -f "${f}" ]; then
      echo "generate-manifest.sh: missing source file ${f}" >&2
      rm -f "${TMP}"
      exit 1
    fi
    digest=$(${HASHER} "${f}" | awk '{print $1}')
    printf '%s  %s\n' "${digest}" "${f}"
  done
} > "${TMP}"

mv -f "${TMP}" "${DEST}"

echo "wrote ${DEST} (${#MANIFESTED_FILES[@]} files)"
