#!/usr/bin/env bash
# IJFW one-time GLOBAL-config cleanup (v1.6.0 P0b remediation).
#
# Pre-1.6.0, session-start.sh authored CLAUDE.md/AGENTS.md relative to the cwd
# with no project-root guard. A session started with cwd == $HOME therefore
# wrote a GLOBAL ~/CLAUDE.md (and ~/AGENTS.md) carrying the IJFW managed block.
# Claude Code loads ~/CLAUDE.md for EVERY project, so that stray write biased
# every repo the user opened (a cross-tenant config bleed).
#
# The P0a cwd guard stops NEW global writes. This script self-heals machines
# that already ran the buggy hook: it strips ONLY the IJFW-managed marker
# regions from the user's GLOBAL CLAUDE.md / AGENTS.md, preserving every
# user-authored line, backs up each file it touches, and drops a sentinel so it
# runs at most once per machine. It NEVER touches project-scoped files.
#
# No `set -e` -- this runs from the SessionStart hot path and must never crash
# Claude Code. Every step guards itself.

IJFW_HOME="${HOME:-}"
[ -z "$IJFW_HOME" ] && exit 0

SENTINEL_DIR="$IJFW_HOME/.ijfw"
SENTINEL="$SENTINEL_DIR/.global-cleanup-v1-done"

# Test/escape hatch: force a re-run by clearing the sentinel.
[ "${IJFW_GLOBAL_CLEANUP_FORCE:-}" = "1" ] && rm -f "$SENTINEL" 2>/dev/null

# Already cleaned -- nothing to do (instant on every subsequent session).
[ -f "$SENTINEL" ] && exit 0

# Strip every IJFW-managed marker region (and the IJFW autogen comment + the
# AGENTS.md "Four IJFW-managed regions" explainer) from $1, preserving all other
# content. Pure text surgery via node (already required for MCP); reads the path
# from argv and never interpolates file content into source.
ijfw_strip_blocks() {
  _file="$1"
  [ -f "$_file" ] || return 0
  node -e '
    const fs = require("fs");
    const file = process.argv[1];
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    let src = fs.readFileSync(file, "utf8");
    const before = src;
    const regions = [
      ["<!-- IJFW-MEMORY-START", "<!-- IJFW-MEMORY-END -->"],
      ["<!-- IJFW-ROUTING-START", "<!-- IJFW-ROUTING-END -->"],
      ["<!-- IJFW-AGENTS-START", "<!-- IJFW-AGENTS-END -->"],
      ["<!-- IJFW-BLACKBOARD-START", "<!-- IJFW-BLACKBOARD-END -->"],
      ["<!-- IJFW-DISCIPLINE-START", "<!-- IJFW-DISCIPLINE-END -->"],
    ];
    for (const [start, end] of regions) {
      const re = new RegExp("\\n*" + esc(start) + "[\\s\\S]*?" + esc(end) + "[^\\n]*", "g");
      src = src.replace(re, "");
    }
    // IJFW autogen comment (CLAUDE.md).
    src = src.replace(/\n*<!-- Auto-generated by IJFW from repo scan\.[^\n]*-->/g, "");
    // AGENTS.md explainer paragraph for the managed regions.
    src = src.replace(/\n*Four IJFW-managed regions live in this file\.[\s\S]*?IJFW will never touch it\./g, "");
    // Collapse the blank-line runs left behind; keep a single trailing newline.
    src = src.replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "") + "\n";
    if (src !== before) {
      fs.writeFileSync(file + ".ijfw-tmp", src);
      fs.renameSync(file + ".ijfw-tmp", file);
    }
  ' "$_file" 2>/dev/null || return 0
}

for _gf in "$IJFW_HOME/CLAUDE.md" "$IJFW_HOME/AGENTS.md"; do
  [ -f "$_gf" ] || continue
  # Only back up + rewrite files that actually carry an IJFW marker region.
  if grep -q "IJFW-MEMORY-START\|IJFW-ROUTING-START\|IJFW-AGENTS-START\|IJFW-BLACKBOARD-START\|IJFW-DISCIPLINE-START" "$_gf" 2>/dev/null; then
    cp "$_gf" "$_gf.ijfw-cleanup-bak" 2>/dev/null
    ijfw_strip_blocks "$_gf"
  fi
done

# Mark done so we never re-scan the home dir on subsequent sessions.
mkdir -p "$SENTINEL_DIR" 2>/dev/null
: > "$SENTINEL" 2>/dev/null
exit 0
