// IJFW v1.5.2 -- brain export + share helpers.
//
// exportPageBundle(repoRoot, slug, outFile)
//   Reads <slug>.md from any of the 4 wiki type dirs, finds [[linked]]
//   wikilinks in the content, inlines each linked page as an "### slug"
//   section after the root. Returns { outFile, bytes, linkedPagesIncluded }.
//
// writeShareReadme(repoRoot)
//   Writes <repoRoot>/ijfw/README.md with team-share instructions
//   (commit ijfw/ to git, teammates clone + `ijfw memory reindex`).
//
// Both functions tolerate the v1->v2 layout transition: they consult the
// layout sentinel via resolveBrainPaths to pick the right wiki location.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { resolveBrainPaths } from './paths.js';
import { validateSafeRepoPath } from './path-guard.js';

const WIKI_TYPES = ['concepts', 'entities', 'decisions', 'milestones'];
// Match the entire bracket-pair content as a single negated character class.
// The slug (left of optional `|`) is extracted in JS after the regex match
// instead of via a nested optional group -- safe-regex flagged the original
// pattern (`[^\]\n|]+(?:\|[^\]\n]*)?`) as potentially unsafe even though it
// can't backtrack catastrophically. This single-class form is provably linear.
const WIKILINK_RE = /\[\[([^\]\n]+)\]\]/g;

function findPage(wikiDir, slug) {
  for (const t of WIKI_TYPES) {
    const p = join(wikiDir, t, `${slug}.md`);
    if (existsSync(p)) return { path: p, type: t };
  }
  return null;
}

function parseWikilinks(md) {
  if (!md) return [];
  const out = new Set();
  for (const m of md.matchAll(WIKILINK_RE)) {
    // The capture group now includes the optional `|alias` suffix; the slug
    // is the substring before the first `|` (matches the original semantics).
    const inner = m[1];
    const pipeIdx = inner.indexOf('|');
    const target = (pipeIdx === -1 ? inner : inner.slice(0, pipeIdx)).trim();
    if (target) out.add(target);
  }
  return [...out];
}

export function exportPageBundle(repoRoot, slug, outFile) {
  // F-LENS2-05 defense-in-depth: brain-handler already validates outFile via
  // validateSafeRepoPath, but exportPageBundle is also exported and may be
  // called directly by future callers. Re-validate here so the policy holds
  // at the writer boundary too.
  const guard = validateSafeRepoPath(repoRoot, outFile);
  if (!guard.ok) return { error: guard.error };
  const paths = resolveBrainPaths(repoRoot);
  const root = findPage(paths.wikiDir, slug);
  if (!root) return { error: 'page-not-found', slug };
  const rootBody = readFileSync(root.path, 'utf8');
  const linked = parseWikilinks(rootBody);

  const parts = [
    `# Export: ${slug}\n\n_Generated by IJFW brain export from ${root.type}/${slug}.md._\n`,
    `## ${slug}\n\n${rootBody.trim()}`,
  ];
  const includedLinks = [];
  for (const target of linked) {
    const found = findPage(paths.wikiDir, target);
    if (!found) continue;
    let body;
    try { body = readFileSync(found.path, 'utf8'); } catch { continue; }
    parts.push(`### ${target}\n\n${body.trim()}`);
    includedLinks.push(target);
  }
  const out = parts.join('\n\n') + '\n';
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out);
  return { outFile, bytes: Buffer.byteLength(out, 'utf8'), linkedPagesIncluded: includedLinks };
}

const SHARE_README = `# Your IJFW Brain

This folder is **your project brain** — durable, queryable knowledge maintained by IJFW across every CLI you use (Claude Code, Codex, Cursor, Windsurf, Gemini, and more).

## Structure

\`\`\`
ijfw/
├── memory/      # raw memory entries (knowledge.md, handoff.md, journal.md, decisions.md)
├── sessions/    # readable per-session logs
├── dump/
│   ├── inbox/      # drop ANY file here (md/txt/transcript/pdf) — gets ingested next dream cycle
│   └── processed/  # files move here once ingested, with a .manifest.json receipt
└── wiki/        # LLM-curated, Obsidian-readable
    ├── concepts/, entities/, decisions/, milestones/
\`\`\`

## Share with your team

1. Commit \`ijfw/\` to git like any other source folder.
2. Teammates clone the repo and run \`ijfw memory reindex\` to populate their local index.
3. The internal index db lives in \`.ijfw/\` (gitignored) — only the content in \`ijfw/\` is shared.

## Privacy

Everything in \`ijfw/\` is plain markdown / json. Inspect it. Edit it. Diff it. Your brain stays under your version control.
`;

export function writeShareReadme(repoRoot) {
  const paths = resolveBrainPaths(repoRoot);
  const out = join(paths.contentDir, 'README.md');
  // F-LENS2-05: validate the share-readme path before writing. A symlinked
  // ijfw/ directory or contentDir resolution outside the repo would otherwise
  // let writeFileSync clobber an arbitrary path.
  const guard = validateSafeRepoPath(repoRoot, out);
  if (!guard.ok) return { error: guard.error };
  mkdirSync(paths.contentDir, { recursive: true });
  writeFileSync(out, SHARE_README);
  return { outFile: out, bytes: Buffer.byteLength(SHARE_README, 'utf8') };
}
