// IJFW v1.5.2 -- brain export + share helpers.
//
// exportPageBundle(repoRoot, slug, outFile)
//   Reads <slug>.md from any of the 4 wiki type dirs, finds [[linked]]
//   wikilinks in the content, inlines each linked page as an "### slug"
//   section after the root. Returns { outFile, bytes, linkedPagesIncluded }.
//
// writeShareReadme(repoRoot)
//   Writes <repoRoot>/ijfw/README.md with team-share instructions
//   (commit ijfw/ to git, teammates clone + `ijfw memory reindex`).
//
// Both functions tolerate the v1->v2 layout transition: they consult the
// layout sentinel via resolveBrainPaths to pick the right wiki location.

import { existsSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { resolveBrainPaths } from './paths.js';
import { validateSafeRepoPath } from './path-guard.js';

const WIKI_TYPES = ['concepts', 'entities', 'decisions', 'milestones'];
// Match the entire bracket-pair content as a single negated character class.
// The slug (left of optional `|`) is extracted in JS after the regex match
// instead of via a nested optional group -- safe-regex flagged the original
// pattern (`[^\]\n|]+(?:\|[^\]\n]*)?`) as potentially unsafe even though it
// can't backtrack catastrophically. This single-class form is provably linear.
const WIKILINK_RE = /\[\[([^\]\n]+)\]\]/g;

function findPage(wikiDir, slug) {
  for (const t of WIKI_TYPES) {
    const p = join(wikiDir, t, `${slug}.md`);
    if (existsSync(p)) return { path: p, type: t };
  }
  return null;
}

function parseWikilinks(md) {
  if (!md) return [];
  const out = new Set();
  for (const m of md.matchAll(WIKILINK_RE)) {
    // The capture group now includes the optional `|alias` suffix; the slug
    // is the substring before the first `|` (matches the original semantics).
    const inner = m[1];
    const pipeIdx = inner.indexOf('|');
    const target = (pipeIdx === -1 ? inner : inner.slice(0, pipeIdx)).trim();
    if (target) out.add(target);
  }
  return [...out];
}

// V155-034 (v1.5.5): export size caps. Wiki pages are written by the dream
// pipeline from user-droppable `dump/inbox/` content, so a poisoned dump can
// produce a page with `[[link1]]...[[linkN]]` plus a few 100MB linked pages.
// Without caps, `wiki.export` concatenates everything into memory and OOMs the
// MCP server. The caps bound:
//   - any single page (root or linked) at MAX_PAGE_BYTES
//   - the total bundle at MAX_BUNDLE_BYTES
// Truncated pages are replaced with a sentinel header so the consumer can
// tell the export was capped, not silently empty.
const MAX_PAGE_BYTES = 2 * 1024 * 1024;     // 2 MB per page
const MAX_BUNDLE_BYTES = 10 * 1024 * 1024;  // 10 MB per bundle

function readPageCapped(filePath) {
  try {
    const st = statSync(filePath);
    if (st.size > MAX_PAGE_BYTES) {
      return {
        truncated: true,
        sizeBytes: st.size,
        body: `[... truncated — page is ${(st.size / 1024 / 1024).toFixed(2)} MB; export cap is ${(MAX_PAGE_BYTES / 1024 / 1024).toFixed(0)} MB ...]`,
      };
    }
    return { truncated: false, sizeBytes: st.size, body: readFileSync(filePath, 'utf8') };
  } catch (e) {
    return { truncated: false, error: e?.message || String(e), body: null };
  }
}

export function exportPageBundle(repoRoot, slug, outFile) {
  // F-LENS2-05 defense-in-depth: brain-handler already validates outFile via
  // validateSafeRepoPath, but exportPageBundle is also exported and may be
  // called directly by future callers. Re-validate here so the policy holds
  // at the writer boundary too.
  const guard = validateSafeRepoPath(repoRoot, outFile);
  if (!guard.ok) return { error: guard.error };
  const paths = resolveBrainPaths(repoRoot);
  const root = findPage(paths.wikiDir, slug);
  if (!root) return { error: 'page-not-found', slug };
  const rootRead = readPageCapped(root.path);
  if (rootRead.body == null) {
    return { error: 'root-page-unreadable', slug, message: rootRead.error };
  }
  const rootBody = rootRead.body;
  const linked = parseWikilinks(rootBody);

  const parts = [
    `# Export: ${slug}\n\n_Generated by IJFW brain export from ${root.type}/${slug}.md._\n`,
    `## ${slug}\n\n${rootBody.trim()}`,
  ];
  let runningBytes = Buffer.byteLength(parts.join('\n\n'), 'utf8');
  const includedLinks = [];
  const truncatedLinks = [];
  const skippedLinks = [];
  let bundleTruncated = false;
  for (const target of linked) {
    if (runningBytes >= MAX_BUNDLE_BYTES) {
      bundleTruncated = true;
      skippedLinks.push(target);
      continue;
    }
    const found = findPage(paths.wikiDir, target);
    if (!found) continue;
    const r = readPageCapped(found.path);
    if (r.body == null) continue;
    const block = `### ${target}\n\n${r.body.trim()}`;
    runningBytes += Buffer.byteLength(block, 'utf8') + 2; // approx '\n\n'
    parts.push(block);
    includedLinks.push(target);
    if (r.truncated) truncatedLinks.push(target);
  }
  if (rootRead.truncated && !truncatedLinks.includes(slug)) truncatedLinks.unshift(slug);

  const out = parts.join('\n\n') + '\n';
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out);
  return {
    outFile,
    bytes: Buffer.byteLength(out, 'utf8'),
    linkedPagesIncluded: includedLinks,
    // Diagnostic fields — only present when caps actually fired so the common
    // case stays terse.
    ...(truncatedLinks.length > 0 ? { truncatedPages: truncatedLinks } : {}),
    ...(bundleTruncated ? { bundleTruncated: true, skippedLinks } : {}),
  };
}

const SHARE_README = `# Your IJFW Brain

This folder is **your project brain** — durable, queryable knowledge maintained by IJFW across every CLI you use (Claude Code, Codex, Cursor, Windsurf, Gemini, and more).

## Structure

\`\`\`
ijfw/
├── memory/      # raw memory entries (knowledge.md, handoff.md, journal.md, decisions.md)
├── sessions/    # readable per-session logs
├── dump/
│   ├── inbox/      # drop ANY file here (md/txt/transcript/pdf) — gets ingested next dream cycle
│   └── processed/  # files move here once ingested, with a .manifest.json receipt
└── wiki/        # LLM-curated, Obsidian-readable
    ├── concepts/, entities/, decisions/, milestones/
\`\`\`

## Share with your team

1. Commit \`ijfw/\` to git like any other source folder.
2. Teammates clone the repo and run \`ijfw memory reindex\` to populate their local index.
3. The internal index db lives in \`.ijfw/\` (gitignored) — only the content in \`ijfw/\` is shared.

## Privacy

Everything in \`ijfw/\` is plain markdown / json. Inspect it. Edit it. Diff it. Your brain stays under your version control.
`;

export function writeShareReadme(repoRoot) {
  const paths = resolveBrainPaths(repoRoot);
  const out = join(paths.contentDir, 'README.md');
  // F-LENS2-05: validate the share-readme path before writing. A symlinked
  // ijfw/ directory or contentDir resolution outside the repo would otherwise
  // let writeFileSync clobber an arbitrary path.
  const guard = validateSafeRepoPath(repoRoot, out);
  if (!guard.ok) return { error: guard.error };
  mkdirSync(paths.contentDir, { recursive: true });
  writeFileSync(out, SHARE_README);
  return { outFile: out, bytes: Buffer.byteLength(SHARE_README, 'utf8') };
}
